// const departments = ["Tech Team", "Marketing", "Product", "Sales", "Customer Service", "Logistics", "Finance"]
const data = [
    {
        name:"Victor Ombeta",
        title:"Senior UI/UX Designer",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in eros congue neque pulvinar egestas. Mauris id lorem eget arcu dictum blandit. Integer ipsum nisi, efficitur ut nisi vitae, consequat ullamcorper lacus. Morbi rutrum imperdiet diam porta commodo. Phasellus tincidunt dictum quam, vel mollis nisl varius a. Sed eget blandit lacus. Aenean purus massa, elementum et gravida nec, tincidunt a ante. Aliquam ex ante, molestie ut maximus quis, dictum interdum dolor. Nam vehicula tempor ante eget facilisis. Phasellus sagittis massa quis sapien mattis, in finibus odio convallis. Nulla laoreet tortor nec neque elementum finibus. Duis rhoncus lacus nec est finibus finibus. Nulla lacinia, ex tempus vehicula feugiat, diam purus pretium est, quis aliquam lectus diam eget turpis. In tincidunt, ligula nec congue bibendum, augue erat rutrum lectus, a tincidunt ligula metus at velit. Ut tempor nibh nec finibus tincidunt. Suspendisse eget nisi a ante posuere ornare sed condimentum dolor.",
   funFact:"Nunc dignissim velit auctor velit pretium ullamcorper. Proin id dapibus tellus, et mattis sapien. Sed eu augue vitae leo ultricies eleifend. Nunc ultrices, nisi ut tristique tincidunt, ligula quam ullamcorper elit, at ullamcorper mauris massa in arcu. Phasellus nec leo tincidunt, tempor odio non, malesuada nisi. Fusce id odio et dolor iaculis varius id quis metus. Nam ut ultricies sapien. Morbi rutrum urna id augue fringilla sagittis. Quisque faucibus eget turpis sed auctor."
    },
    {
        name:"John Doe",
        title:"Senior UI/UX Designer",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in eros congue neque pulvinar egestas. Mauris id lorem eget arcu dictum blandit. Integer ipsum nisi, efficitur ut nisi vitae, consequat ullamcorper lacus. Morbi rutrum imperdiet diam porta commodo. Phasellus tincidunt dictum quam, vel mollis nisl varius a. Sed eget blandit lacus. Aenean purus massa, elementum et gravida nec, tincidunt a ante. Aliquam ex ante, molestie ut maximus quis, dictum interdum dolor. Nam vehicula tempor ante eget facilisis. Phasellus sagittis massa quis sapien mattis, in finibus odio convallis. Nulla laoreet tortor nec neque elementum finibus. Duis rhoncus lacus nec est finibus finibus. Nulla lacinia, ex tempus vehicula feugiat, diam purus pretium est, quis aliquam lectus diam eget turpis. In tincidunt, ligula nec congue bibendum, augue erat rutrum lectus, a tincidunt ligula metus at velit. Ut tempor nibh nec finibus tincidunt. Suspendisse eget nisi a ante posuere ornare sed condimentum dolor.",
   funFact:"Nunc dignissim velit auctor velit pretium ullamcorper. Proin id dapibus tellus, et mattis sapien. Sed eu augue vitae leo ultricies eleifend. Nunc ultrices, nisi ut tristique tincidunt, ligula quam ullamcorper elit, at ullamcorper mauris massa in arcu. Phasellus nec leo tincidunt, tempor odio non, malesuada nisi. Fusce id odio et dolor iaculis varius id quis metus. Nam ut ultricies sapien. Morbi rutrum urna id augue fringilla sagittis. Quisque faucibus eget turpis sed auctor."
    },
    {
        name:"Jane Doe",
        title:"Senior UI/UX Designer",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in eros congue neque pulvinar egestas. Mauris id lorem eget arcu dictum blandit. Integer ipsum nisi, efficitur ut nisi vitae, consequat ullamcorper lacus. Morbi rutrum imperdiet diam porta commodo. Phasellus tincidunt dictum quam, vel mollis nisl varius a. Sed eget blandit lacus. Aenean purus massa, elementum et gravida nec, tincidunt a ante. Aliquam ex ante, molestie ut maximus quis, dictum interdum dolor. Nam vehicula tempor ante eget facilisis. Phasellus sagittis massa quis sapien mattis, in finibus odio convallis. Nulla laoreet tortor nec neque elementum finibus. Duis rhoncus lacus nec est finibus finibus. Nulla lacinia, ex tempus vehicula feugiat, diam purus pretium est, quis aliquam lectus diam eget turpis. In tincidunt, ligula nec congue bibendum, augue erat rutrum lectus, a tincidunt ligula metus at velit. Ut tempor nibh nec finibus tincidunt. Suspendisse eget nisi a ante posuere ornare sed condimentum dolor.",
   funFact:"Nunc dignissim velit auctor velit pretium ullamcorper. Proin id dapibus tellus, et mattis sapien. Sed eu augue vitae leo ultricies eleifend. Nunc ultrices, nisi ut tristique tincidunt, ligula quam ullamcorper elit, at ullamcorper mauris massa in arcu. Phasellus nec leo tincidunt, tempor odio non, malesuada nisi. Fusce id odio et dolor iaculis varius id quis metus. Nam ut ultricies sapien. Morbi rutrum urna id augue fringilla sagittis. Quisque faucibus eget turpis sed auctor."
    },
    {
        name:"Victor Ombeta",
        title:"Senior UI/UX Designer",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in eros congue neque pulvinar egestas. Mauris id lorem eget arcu dictum blandit. Integer ipsum nisi, efficitur ut nisi vitae, consequat ullamcorper lacus. Morbi rutrum imperdiet diam porta commodo. Phasellus tincidunt dictum quam, vel mollis nisl varius a. Sed eget blandit lacus. Aenean purus massa, elementum et gravida nec, tincidunt a ante. Aliquam ex ante, molestie ut maximus quis, dictum interdum dolor. Nam vehicula tempor ante eget facilisis. Phasellus sagittis massa quis sapien mattis, in finibus odio convallis. Nulla laoreet tortor nec neque elementum finibus. Duis rhoncus lacus nec est finibus finibus. Nulla lacinia, ex tempus vehicula feugiat, diam purus pretium est, quis aliquam lectus diam eget turpis. In tincidunt, ligula nec congue bibendum, augue erat rutrum lectus, a tincidunt ligula metus at velit. Ut tempor nibh nec finibus tincidunt. Suspendisse eget nisi a ante posuere ornare sed condimentum dolor.",
   funFact:"Nunc dignissim velit auctor velit pretium ullamcorper. Proin id dapibus tellus, et mattis sapien. Sed eu augue vitae leo ultricies eleifend. Nunc ultrices, nisi ut tristique tincidunt, ligula quam ullamcorper elit, at ullamcorper mauris massa in arcu. Phasellus nec leo tincidunt, tempor odio non, malesuada nisi. Fusce id odio et dolor iaculis varius id quis metus. Nam ut ultricies sapien. Morbi rutrum urna id augue fringilla sagittis. Quisque faucibus eget turpis sed auctor."
    }
]